# golangci-lint v2 configuration for auto-worktree
# https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  tests: true
  build-tags: []
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout

linters:
  default: none
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis tool (includes gosimple in v2)
    - unused        # Check for unused constants, variables, functions and types

    # Additional recommended linters
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Report unused function parameters
    - gocyclo       # Compute and check the cyclomatic complexity of functions
    - goconst       # Find repeated strings that could be replaced by a constant
    - dupl          # Tool for code clone detection
    - gosec         # Inspect source code for security problems
    - gocritic      # Provides diagnostics that check for bugs, performance and style issues
    - gocognit      # Compute and check the cognitive complexity of functions
    - bodyclose     # Check whether HTTP response body is closed successfully
    - noctx         # Find sending http request without context.Context
    - copyloopvar   # Check for pointers to enclosing loop variables
    - prealloc      # Find slice declarations that could potentially be pre-allocated
    - predeclared   # Find code that shadows one of Go's predeclared identifiers
    - whitespace    # Detection of leading and trailing whitespace
    - wsl           # Whitespace Linter - Forces you to use empty lines!

  disable:
    - godox         # Detect FIXME, TODO and other comment tags
    - testpackage   # Makes you use a separate _test package
    - nlreturn      # Checks for a new line before return and branch statements
    - exhaustive    # Check exhaustiveness of enum switch statements
    - exhaustruct   # Checks if all structure fields are initialized
    - tagliatelle   # Check struct tags
    - varnamelen    # Checks that the length of a variable's name matches its scope
    - ireturn       # Accept Interfaces, Return Concrete Types
    - cyclop        # Checks function and package cyclomatic complexity
    - funlen        # Tool for detection of long functions
    - lll           # Reports long lines
    - gochecknoglobals # Check that no global variables exist
    - gochecknoinits   # Check that no init functions exist
    - nestif        # Reports deeply nested if statements
    - maintidx      # Measures the maintainability index of each function
    - mnd           # Detects magic numbers

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Minor optimization, not critical
      settings:
        shadow:
          strict: false

    misspell:
      locale: US

    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    dupl:
      threshold: 100

    goconst:
      min-len: 3
      min-occurrences: 3

    gosec:
      excludes:
        - G204  # Audit use of command execution - we need this for git commands

    gocritic:
      enabled-checks:
        - appendAssign
        - assignOp
        - boolExprSimplify
        - captLocal
        - caseOrder
        - commentedOutCode
        - defaultCaseOrder
        - dupArg
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - elseif
        - emptyFallthrough
        - exitAfterDefer
        - flagDeref
        - flagName
        - hexLiteral
        - ifElseChain
        - indexAlloc
        - methodExprCall
        - nilValReturn
        - offBy1
        - rangeExprCopy
        - rangeValCopy
        - regexpMust
        - singleCaseSwitch
        - sloppyLen
        - switchTrue
        - typeSwitchVar
        - underef
        - unlabelStmt
        - unlambda
        - unslice
        - valSwap
        - wrapperFunc

    whitespace:
      multi-if: false
      multi-func: false

    wsl:
      allow-assign-and-call: true
      allow-cuddle-declarations: true
      allow-multiline-assign: true
      allow-separated-leading-comment: false
      allow-trailing-comment: true
      force-case-trailing-whitespace: 0
      force-err-cuddling: false
      force-short-decl-cuddling: false

  exclusions:
    paths:
      - vendor
      - .git
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - goconst
          - wsl

      # Exclude known linters from partially hard-vendored code
      - path: internal/hmac/
        text: "weak cryptographic primitive"
        linters:
          - gosec

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true

    goimports:
      local-prefixes:
        - github.com/kaeawc/auto-worktree

  exclusions:
    paths:
      - vendor
      - .git

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
  fix: false
